version: '3.7'
name: familyapp-dev-env
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5432:5432'
    networks:
      - api
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rootdb

  server:
    image: familyapp
    container_name: server-express
    restart: always
    depends_on:
      - postgres
    networks:
      - api
    ports:
      - 3000:3000

volumes:
  pgdata:

networks:
  api: